// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkteddtfsppevqotrrgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrdGVkZHRmc3BwZXZxb3RycmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NzU0OTcsImV4cCI6MjA1NTQ1MTQ5N30.di5Ki1EAiZcm8aj3hw61L-5wQi3iRCmqM5JgHgTB48A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);